#MossFrp配置文件
#插件&客户端开发者：B站_墨守MossCG
#本配置文件兼容插件版本及独立端版本

#语言选项
#填写的时候请注意大小写
#支持的语言如下：
#zh_cn en_us
language: zh_cn

#报错显示方式
#light为简化报错
#full为完整报错
exceptionMode: full

#系统类型
#一般来说默认auto就行
#如果自动判断不对，那就自己填系统名称
#请复制下方的名称填入，若你填了个不知道啥就默认判断windows
#auto
#windows
#linux
systemType: auto