name: MossFrp
version: V1.4.2.1.1513 Beta
main: org.mossmc.mosscg.MossFrp.PathPlugin
author: MossCG
description: A plugin which can run Frp with server.
commands:
  MossFrp:
    description: MossFrp主指令
permissions:
  mossfrp.help:
    description: 帮助信息显示权限
    default: op
